name: activity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [debian-10, debian-11]  # Specify Debian versions
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js for Debian
      run: |
        echo "Setting up Node.js version ${{ matrix.node-version }} on ${{ matrix.os }}"
        curl -fsSL https://deb.nodesource.com/setup_${{ matrix.node-version }}.x | sudo -E bash -
        sudo apt-get install -y nodejs
    - name: Verify Node.js version
      run: node -v
    - name: Verify npm version
      run: npm -v
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --reporter=spec
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./path-to-output
