name: activity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # ใช้ runner ที่มีอยู่
    strategy:
      matrix:
        os: [ubuntu-latest, debian:latest, centos:latest]  # รวม OS ที่ต้องการทดสอบ
        node-version: [18, 20, 22]

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # ตรวจสอบโค้ดจาก repository

      - name: Set up Node.js in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ${matrix.os} /bin/sh -c "
            curl -fsSL https://deb.nodesource.com/setup_${{ matrix.node-version }}.x | bash - &&
            apt-get install -y nodejs npm &&  # สำหรับ Ubuntu และ Debian
            npm ci &&  # ติดตั้ง dependencies
            npm test   # รัน test suite
          "

      - name: Install Node.js and Run Tests on CentOS
        if: startsWith(matrix.os, 'centos')
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app centos:latest /bin/sh -c "
            yum install -y nodejs npm &&  # ติดตั้ง Node.js และ npm สำหรับ CentOS
            npm ci &&  # ติดตั้ง dependencies
            npm test   # รัน test suite
          "
