name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [debian-latest, centos-latest]  # ระบบปฏิบัติการที่ต้องการทดสอบ
        node-version: [18.x, 20.x, 22.x]  # เวอร์ชันของ Node.js ที่ต้องการทดสอบ

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # ตรวจสอบโค้ดจาก repository

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}  # ตั้งค่าเวอร์ชัน Node.js ตามที่ระบุใน matrix
          cache: 'npm'  # ใช้ cache สำหรับ npm เพื่อเพิ่มประสิทธิภาพ

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "debian-latest" ]]; then
            npm ci  # ติดตั้ง dependencies สำหรับ Ubuntu และ Debian
          else
            sudo yum install -y nodejs npm  # ติดตั้ง Node.js และ npm สำหรับ CentOS
            npm ci  # ติดตั้ง dependencies หลังจากติดตั้ง Node.js
          fi

      - name: Run tests
        run: npm test  # รัน test suite เพื่อตรวจสอบความถูกต้องของแอปพลิเคชัน
