name: Activity

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Specify the operating systems
        node-version: [18.x, 20.x, 22.x]  # Specify the Node.js versions
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then npm install --legacy-peer-deps; else npm ci; fi
      
      - name: Build the project (if applicable)
        run: npm run build --if-present

      - name: Run tests
        run: npm test
