name: activity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest, centos-latest] # Specify your desired Linux distributions
        node-version: [18.x, 20.x, 22.x]  # Specify Node.js versions

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
